/*
 * Ververica Platform API
 * The Ververica Platform APIs, excluding Application Manager.
 *
 * OpenAPI spec version: 2.7.0
 * Contact: platform@ververica.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.getindata.ververica.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.getindata.ververica.client.model.Catalog;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ListCatalogsResponse
 */

public class ListCatalogsResponse {
  @JsonProperty("catalogs")
  private List<Catalog> catalogs = null;

  public ListCatalogsResponse catalogs(List<Catalog> catalogs) {
    this.catalogs = catalogs;
    return this;
  }

  public ListCatalogsResponse addCatalogsItem(Catalog catalogsItem) {
    if (this.catalogs == null) {
      this.catalogs = new ArrayList<Catalog>();
    }
    this.catalogs.add(catalogsItem);
    return this;
  }

   /**
   * Get catalogs
   * @return catalogs
  **/
  @ApiModelProperty(value = "")
  public List<Catalog> getCatalogs() {
    return catalogs;
  }

  public void setCatalogs(List<Catalog> catalogs) {
    this.catalogs = catalogs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListCatalogsResponse listCatalogsResponse = (ListCatalogsResponse) o;
    return Objects.equals(this.catalogs, listCatalogsResponse.catalogs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(catalogs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListCatalogsResponse {\n");
    
    sb.append("    catalogs: ").append(toIndentedString(catalogs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

