/*
 * Ververica Platform API
 * The Ververica Platform APIs, excluding Application Manager.
 *
 * OpenAPI spec version: 2.7.0
 * Contact: platform@ververica.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.getindata.ververica.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.getindata.ververica.client.model.VvpColumn;
import com.getindata.ververica.client.model.VvpUniqueConstraint;
import com.getindata.ververica.client.model.VvpWatermark;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * VvpSchema
 */

public class VvpSchema {
  @JsonProperty("column")
  private List<VvpColumn> column = null;

  @JsonProperty("primaryKey")
  private VvpUniqueConstraint primaryKey = null;

  @JsonProperty("watermarkSpec")
  private List<VvpWatermark> watermarkSpec = null;

  public VvpSchema column(List<VvpColumn> column) {
    this.column = column;
    return this;
  }

  public VvpSchema addColumnItem(VvpColumn columnItem) {
    if (this.column == null) {
      this.column = new ArrayList<VvpColumn>();
    }
    this.column.add(columnItem);
    return this;
  }

   /**
   * Get column
   * @return column
  **/
  @ApiModelProperty(value = "")
  public List<VvpColumn> getColumn() {
    return column;
  }

  public void setColumn(List<VvpColumn> column) {
    this.column = column;
  }

  public VvpSchema primaryKey(VvpUniqueConstraint primaryKey) {
    this.primaryKey = primaryKey;
    return this;
  }

   /**
   * Get primaryKey
   * @return primaryKey
  **/
  @ApiModelProperty(value = "")
  public VvpUniqueConstraint getPrimaryKey() {
    return primaryKey;
  }

  public void setPrimaryKey(VvpUniqueConstraint primaryKey) {
    this.primaryKey = primaryKey;
  }

  public VvpSchema watermarkSpec(List<VvpWatermark> watermarkSpec) {
    this.watermarkSpec = watermarkSpec;
    return this;
  }

  public VvpSchema addWatermarkSpecItem(VvpWatermark watermarkSpecItem) {
    if (this.watermarkSpec == null) {
      this.watermarkSpec = new ArrayList<VvpWatermark>();
    }
    this.watermarkSpec.add(watermarkSpecItem);
    return this;
  }

   /**
   * Get watermarkSpec
   * @return watermarkSpec
  **/
  @ApiModelProperty(value = "")
  public List<VvpWatermark> getWatermarkSpec() {
    return watermarkSpec;
  }

  public void setWatermarkSpec(List<VvpWatermark> watermarkSpec) {
    this.watermarkSpec = watermarkSpec;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VvpSchema vvpSchema = (VvpSchema) o;
    return Objects.equals(this.column, vvpSchema.column) &&
        Objects.equals(this.primaryKey, vvpSchema.primaryKey) &&
        Objects.equals(this.watermarkSpec, vvpSchema.watermarkSpec);
  }

  @Override
  public int hashCode() {
    return Objects.hash(column, primaryKey, watermarkSpec);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VvpSchema {\n");
    
    sb.append("    column: ").append(toIndentedString(column)).append("\n");
    sb.append("    primaryKey: ").append(toIndentedString(primaryKey)).append("\n");
    sb.append("    watermarkSpec: ").append(toIndentedString(watermarkSpec)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

