/*
 * Ververica Platform API
 * The Ververica Platform APIs, excluding Application Manager.
 *
 * OpenAPI spec version: 2.7.0
 * Contact: platform@ververica.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.getindata.ververica.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * VvpWatermark
 */

public class VvpWatermark {
  @JsonProperty("timeColumn")
  private String timeColumn = null;

  @JsonProperty("watermarkExpression")
  private String watermarkExpression = null;

  @JsonProperty("watermarkType")
  private String watermarkType = null;

  public VvpWatermark timeColumn(String timeColumn) {
    this.timeColumn = timeColumn;
    return this;
  }

   /**
   * Get timeColumn
   * @return timeColumn
  **/
  @ApiModelProperty(value = "")
  public String getTimeColumn() {
    return timeColumn;
  }

  public void setTimeColumn(String timeColumn) {
    this.timeColumn = timeColumn;
  }

  public VvpWatermark watermarkExpression(String watermarkExpression) {
    this.watermarkExpression = watermarkExpression;
    return this;
  }

   /**
   * Get watermarkExpression
   * @return watermarkExpression
  **/
  @ApiModelProperty(value = "")
  public String getWatermarkExpression() {
    return watermarkExpression;
  }

  public void setWatermarkExpression(String watermarkExpression) {
    this.watermarkExpression = watermarkExpression;
  }

  public VvpWatermark watermarkType(String watermarkType) {
    this.watermarkType = watermarkType;
    return this;
  }

   /**
   * Get watermarkType
   * @return watermarkType
  **/
  @ApiModelProperty(value = "")
  public String getWatermarkType() {
    return watermarkType;
  }

  public void setWatermarkType(String watermarkType) {
    this.watermarkType = watermarkType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VvpWatermark vvpWatermark = (VvpWatermark) o;
    return Objects.equals(this.timeColumn, vvpWatermark.timeColumn) &&
        Objects.equals(this.watermarkExpression, vvpWatermark.watermarkExpression) &&
        Objects.equals(this.watermarkType, vvpWatermark.watermarkType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeColumn, watermarkExpression, watermarkType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VvpWatermark {\n");
    
    sb.append("    timeColumn: ").append(toIndentedString(timeColumn)).append("\n");
    sb.append("    watermarkExpression: ").append(toIndentedString(watermarkExpression)).append("\n");
    sb.append("    watermarkType: ").append(toIndentedString(watermarkType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

