name: Prepare release branch

on: workflow_dispatch

jobs:
  prepare-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Save current version
        id: save_current_version
        run: |
          mvn versions:set -DremoveSnapshot -DgenerateBackupPoms=false
          echo "::set-output name=current_version::$(mvn -B help:evaluate -Dexpression=project.version -q -DforceStdout)"

      - name: Update the CHANGELOG according to 'Keep a Changelog' guidelines
        uses: thomaseizinger/keep-a-changelog-new-release@v1
        with:
          version: ${{ steps.save_current_version.outputs.current_version }}

      - name: Create a new release branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Bump CHANGELOG for release ${{ steps.save_current_version.outputs.current_version }}"
          git checkout -b release/1.15-${{ steps.save_current_version.outputs.current_version }}
          git push -u origin release/1.15${{ steps.save_current_version.outputs.current_version }}
